apiVersion: batch/v1
kind: CronJob
metadata:
  name: es-snapshot
spec:
  schedule: "0 0 * * *" # every 24 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: es-curl
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["/bin/sh", "-c"]
            args: [ "curl -X PUT \"http://elasticsearch-master:9200/_snapshot/s3_backups/%3Csnapshot-%7Bnow%2Fd%7D%3E?pretty\"" ]
          restartPolicy: OnFailure