apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hava.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}-web
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hava.name" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum.helm.kubernetes.io/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum.helm.kubernetes.io/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "hava.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/hava/bin/hava"]
          args: ["exec", "web"]
          volumeMounts:
          - name: license
            mountPath: /hava/license
            readOnly: true
          resources:
            requests:
              cpu: {{ .Values.web.cpu }}
            limits:
              memory: {{ .Values.web.memory}}
          envFrom:
          - configMapRef:
              name: {{ include "hava.fullname" . }}-environment
          env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "hava.fullname" . }}-environment
                key: "DATABASE_URL"
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "hava.fullname" . }}-environment
                key: "REDIS_URL"
          - name: AZURE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "azure-secret-key"
          - name: CAR_USER_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "car-user-secret-key"
          - name: ELASTICSEARCH_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "elasticsearch-pass"
          - name: ENCRYPT_IV
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "encrypt-iv"
          - name: ENCRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "encrypt-key"
          - name: IMAGES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "images-secret-key"
          - name: RENDER_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "s3-secret-access-key"
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "smtp-email-pass"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "web-secret-key"
          - name: EMBEDDABLE_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "hava.fullname" . }}-secrets
                key: "embed-signing-key"
          ports:
            - name: http
              containerPort: 9700
              protocol: TCP
            - name: websocket
              containerPort: 9701
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health_check
              port: 9700
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: license
        secret:
          secretName: {{ include "hava.fullname" . }}-license
          items:
          - key: license
            path: license
