{{- if .Values.web.ingress.enable }}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: aws-load-balancer
spec:
  controller: ingress.k8s.aws/alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hava.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "hava.fullname" . }}-ingress
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: 200,404
    {{ if eq .Values.environment.ssl "true" }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.web.ingress.acm_cert_arn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{ else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{ end }}
spec:
  ingressClassName: aws-load-balancer
  defaultBackend:
    service:
      name: {{ include "hava.fullname" . }}-web
      port: 
        number: 9700
  rules:
    - host: {{ include "hava.webHostName" . }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hava.fullname" . }}-web
              port:
                number: 9700
    - host: {{ include "hava.websocketHostName" . }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hava.fullname" . }}-websocket
              port:
                number: 9701
    - host: {{ include "hava.apiHostName" . }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "hava.fullname" . }}-web
              port:
                number: 9700
{{- end }}