apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hava.fullname" . }}-install
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      annotations:
        checksum.helm.kubernetes.io/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum.helm.kubernetes.io/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "hava.name" . }}-install
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: setup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: ["hava exec rake db:setup && hava exec rake es:index && hava accounts setup {{ .Values.setup.default_user }} {{ .Values.setup.default_email }} && curl -X PUT \"http://elasticsearch-master:9200/_snapshot/s3_backups?pretty\" -H 'Content-Type: application/json' -d'{ \"type\": \"s3\", \"settings\": { \"bucket\": \"{{ .Values.elasticsearch.backup_bucket_name }}\" } }'"]
        resources:
          requests:
            cpu: 500m
          limits:
            memory: 1024M
        envFrom:
        - configMapRef:
            name: {{ include "hava.fullname" . }}-environment
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "hava.fullname" . }}-environment
              key: "DATABASE_URL"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "hava.fullname" . }}-environment
              key: "REDIS_URL"
        - name: ELASTICSEARCH_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "hava.fullname" . }}-environment
              key: "ELASTICSEARCH_URL"
