apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hava.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  encrypt-iv: {{ required "Encryption IV required, please set encryption.iv in config file." .Values.encryption.iv | quote }}
  encrypt-key: {{ required "Encryption Key required, please set encryption.key in config file." .Values.encryption.key | quote }}
  car-user-secret-key: {{ .Values.import.aws.secret_key | quote }}
  web-secret-key: {{ required "Encryption web key required, please set encryption.web_key in config file." .Values.encryption.web_key | quote }}
  database-pass: {{ required "Database password needs to be set, please set database.password in the config file" .Values.database.password | quote }}
  elasticsearch-pass: {{ .Values.elasticsearch.password | quote }}
  {{- if .Values.email.smtp.pass }}
  smtp-email-pass: {{ .Values.email.smtp.pass | quote }}
  {{- end }}
  images-secret-key: {{ .Values.render.aws.secret_key | quote }}
  {{- if not .Values.render.aws.use_sa_role }}
  s3-secret-access-key: {{ required "An s3 secret key is required for storing environment renders. Use 'render.aws.secret_key' to set it" .Values.render.aws.secret_key | quote }}
  {{- else }}
  s3-secret-access-key: "dummy"
  {{- end }}
  auth0-secret: {{ .Values.environment.auth0.secret | quote }}
  {{- if .Values.database.host }}
  DATABASE_URL: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  {{- else }}
  DATABASE_URL: "postgres://hava:hava@{{ include "hava.fullname" . }}-db:5432/{{ .Values.database.name }}"
  {{- end }}