apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hava.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  encrypt-iv: {{ .Values.encryption.iv | quote }}
  encrypt-key: {{ .Values.encryption.key | quote }}
  azure-secret-key: {{ .Values.import.azure.secret_key | quote }}
  car-user-secret-key: {{ .Values.import.aws.secret_key | quote }}
  secret-key: {{ .Values.web.secret_key | quote }}
  database-pass: {{ .Values.database.password | quote }}
  elasticsearch-pass: {{ .Values.elasticsearch.password | quote }}
  embed-signing-key: {{ .Values.embed.signing_key | quote }}
  smtp-email-pass: {{ .Values.email.smtp.pass | quote }}
  gcp-private-key: {{ .Values.gcp.private_key | quote }}
  images-secret-key: {{ .Values.render.aws.secret_key | quote }}
  s3-secret-access-key: {{ .Values.render.aws.secret_key | quote }}
  es-secret-access-key: {{ required "An s3 access key id is required for Elasticsearch backups. Use 'elasticsearch.backup.access_key' to set it" .Values.elasticsearch.backup.access_key | quote }}
  es-secret-secret-key: {{ required "An s3 secret key is required for Elasticsearch backups. Use 'elasticsearch.backup.secret_key' to set it" .Values.elasticsearch.backup.secret_key | quote }}
