apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hava.fullname" . }}-license
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  license: {{ required "A license file needs to be passed in to install this template. '--set-file license=<path to license>'" .Values.license | quote }}