# This block of validation is in place because we need to pass the secret names and keys to the subchart 
# which we have to do through the values.yaml file. We can't use conditionals there, so the secrets 
# must always exist, even if they are empty. We use manual validation here rather than where it's inserted
# to make sure good feedback is provided during helm execution only when there is an actual problem
{{- if .Values.elasticsearch.backup.enabled }}
  {{- if not .Values.elasticsearch.backup.access_key }}
    {{ fail "An s3 access key id is required for Elasticsearch backups. Use 'elasticsearch.backup.access_key' to set it" }}
  {{- end }}
  {{- if not .Values.elasticsearch.backup.secret_key }}
    {{ fail "An s3 secret key is required for Elasticsearch backups. Use 'elasticsearch.backup.secret_key' to set it" }}
  {{- end}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets # hard coded because helm doesn't support dynamic values in values file, and this name needs to be passed to the elasticsearch subchart
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{- if .Values.elasticsearch.backup.enabled }}
  es-secret-access-key: {{ .Values.elasticsearch.backup.access_key | quote }}
  es-secret-secret-key: {{ .Values.elasticsearch.backup.secret_key | quote }}
  {{- else }}
  es-secret-access-key: "dummy"
  es-secret-secret-key: "dummy"
  {{- end }}
