---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hava.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}-web
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 9700
      targetPort: 9700
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hava.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
