{{- if .Values.cache.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hava.fullname" . }}-redis
  labels:
    {{- include "hava.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "hava.name" . }}-redis
spec:
  ports:
    - port: 6379
  selector:
    app.kubernetes.io/name: {{ include "hava.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}