{{- if .Values.serviceaccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hava.serviceaccount.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}-sa
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.serviceaccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- end }}