{{- if .Values.cache.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hava.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "hava.name" . }}-redis
    helm.sh/chart: {{ include "hava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hava.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hava.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-redis
        image: redis:4.0-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.cache.storage_class | quote }}
      resources:
        requests:
          cpu: "100m"
          memory: "128M"
          storage: 4Gi
{{- end }}
