# Default values for hava.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

setup:
  default_user: hava
  default_email: hava@example.com

environment:
  type: "bob"
  domain: "example.com"

image:
  repository: hava/self-hosted
  tag: 2.0.237
  pullPolicy: IfNotPresent

web:
  replicas: 1
  concurrency: 2
  pool: 5
  threads: 2
  lifetime: 1440
  cpu: 300m
  memory: 1536M
  secret_key: "example"
  icons:
    scheme: http
    host: app.example.com
    port: 80 
    path: /tmp
  ingress:
    # enabled default ingress, set to false to configure different ingress, e.g. gloo nginx
    enable: true

import:
  replicas: 1
  concurrency: 2
  pool: 40
  lifetime: 9000
  auto_sync:
    enabled: true
    count: 30
    minutes: 1440
  azure:
    client_id: "example"
    subscription_id: "example"
    tenant_id: "example"
    secret_key: "example"
  aws:
    account_id: "example"
    access_key: "example"
    secret_key: "example"

build:
  concurrency: 2
  lifetime: 1440
  pool: 40
  replicas: 1

clock:
  concurrency: 2
  lifetime: 1440
  pool: 40
  replicas: 1

render:
  concurrency: 2
  lifetime: 1440
  pool: 40
  replicas: 1
  aws:
    access_key: "example"
    bucket: "example"
    region: "example"
    secret_key: "example"

worker:
  concurrency: 2
  lifetime: 1440
  pool: 40
  replicas: 1

report:
  concurrency: 2
  lifetime: 1440
  pool: 40
  replicas: 1
  cloudmapper_path: "example"

maintenance:
  concurrency: 2
  lifetime: 1440
  pool: 40
  replicas: 1

assets:
  cdn: "app.example.com"

database:
  host: "hava2.cxouiktzim2e.us-east-1.rds.amazonaws.com"
  port: 5432
  user: "postgres"
  password: "havahava"

embed:
  signing_key: "example"


email: 
  smtp:
    user: "example"
    pass: "example"
    port: 53
    domain: "example.com"
    address: "example.com"
    from_address: "noreply@example.com"
    from_name: "No Reply"

gcp:
  private_key: "example"

cache:
  ## set to false if hosting redis externally. e.g. memstore paas
  enabled: true

# persistent storage configuration
storage:
  ## if the chart will define storage classes or not
  enable: true
  ## type of persistent storage, supported values: AWS, GCP, Azure, local
  type: AWS

elasticsearch:
  ## set to false if hosting elasticsearch externally
  enabled: true
  replicas: 3
  password: "example"
  volumeClaimTemplate:
    storageClassName: hava-ssd
    resources:
      requests:
        storage: 200Gi

encryption:
  iv: "iv"
  key: "key"